on:
  push:
    branches: main
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make
    - uses: actions/upload-artifact@v2
      with:
        name: wasmfiles
        path: "*.wasm"
